### ISSUE TITLE
 웹페이지 가지고  APk 단말 패키지 만들기

### ISSUE THREAD

**Issue by sangwoongLee** [hanwool-chruch/app-hanwool#1]
## 설명 
 웹페이지 가지고  APk 단말 패키지 만들기
 WEB APP 
## 체크리스트
- [ ] 
- [ ]

**Comment by sangwoongLee** [comment]
이미 웹페이지를 Android  APP 나 IOS APP 으로 만들어 주는 회사들이 많이 있음
http://www.swing2app.co.kr/

기본적으로는 APK 를 만들어 주는 것은 공짜이나 스토어에 올리기 위해서는 비용이 발생함

 - 안드로이드 웹까지는 공짜이나
 - IOS은 패키지가 만들어지는 확인 못함

- 소스 개발로 Android 개발할지 고민해야 할것 같음

**Comment by pleasenara** [comment]
**회계관리 프로그램 ver1**
1. 권한
모든 청년들이 접근이 가능할 필요는 없음. 그렇다고 까다롭게 굴 필요도 없으니
회원가입시 선택정보로 회계처리 필요 Y --> 소속, 입금받을 계좌, 계좌명, 예금주 이렇게 쓰도록
소속 콤보박스, 입금 계좌 콤보박스
그래서 회계처리 필요 flag에 따라서 결제 작성 버튼 활성화 및 비활성화?
메인화면에서 회계버튼이 모든 사람에게 보일필요가 있나?

2. 사용조직
- 임원들
- 찬양팀은? 찬양팀은 한사람이 주로 결제하는 상황이 많음.
- 방송회비? 올해 처음 도입되어서 정해진 룰이 없음. 마찬가지로 사용내역 정리해서 공유되어야 함.
- 리더들 심방비, 목사님의 심방비??

3. 프로세스
- 사용내역을 등록할 때 자신이 어떤 소속으로 어떤 목적으로 얼마를 어떤 내용으로 언제(등록일이 결제일과 다를 수 있으므로)사용했는지를 작성해야 함.
- 다른 팀의 결제 내역까지 보일필요는 x(본인이 설정한 소속 내역만)

**추가기능**
1. 처리상태
- 등록, 입금 요청 중, 송금 완료 등. 결재: 회계의 책임을 덜어주기 위해(회계는 청구를 하면 줄 수 밖에 없음)
그럼 회계가 그 결제 내역을 보고 사용자에 연결된 계좌로 송금.
그리고 반드시 해당 결제 내역에 대해 송금완료 표시를 해야하고.
- 약속할 것: 24시간 안에 송금해주겠다.(결재 등)
- 문자 알림
여기까진 일단 ver1

2. 파일첨부기능
결제 내역등록할 때 파일 첨부 기능도 넣어서 영수증 사진 첨부

3. 엑셀파일 다운로드
있어야 할 컬럼: 일자, 거래처, 적요, 수입, 지출, 잔액, 관련행사, 영수증넘버링?, 증빙유무

**ver2**
나중엔 다 필요없고 OCR로다가 걍 빡!

-------------------------------------------------------------------------------
http://blog.naver.com/tnvlfrla/220351004017 --만들어주는 사이트
https://noa-xyz.tistory.com/21 --안드로이드 스튜디오에서 직접 만드는 방법
